Deprecate UI package
meteor/blaze pull request #391
Opened 2022-08-26 06:49 UTC by jankapunkt

Added the deprecated flag to the package.js file

2022-08-26 14:36 UTC, StorytellerCZ approved these changes

2022-08-27 09:47 UTC, jankapunkt commented
@StorytellerCZ should we target 3.0 or 2.6.2?

2022-08-28 20:51 UTC, StorytellerCZ requested changes

2022-08-28 20:51 UTC, StorytellerCZ commented on packages/ui/package.js
>    version: '1.0.13',
We should probably bump the version here and publish the package so that the warning gets out.

2022-08-28 20:52 UTC, StorytellerCZ commented
Good question @jankapunkt. I think version 3 is more appropriate for this.

2022-09-26 06:57 UTC, merged