Completed GitHub community standards
meteor/blaze pull request #422
Opened 2023-06-05 15:54 UTC by Veldergard

My first pull request

Issue #420 
- Code of conduct
- Security policy
- Issue template
- Pull request template

2023-06-05 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/blaze?pullRequest=422) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/blaze?pullRequest=422) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/blaze?pullRequest=422) it.</sub>

2023-06-05 20:42 UTC, jankapunkt requested changes
Please change the commented sections, from my end the rest looks good. I think this still needs at least approval from a core member @Grubba27 @denihs especially on the Security Policy and if reporting to security@meteor.com is the right action here.

2023-06-05 20:42 UTC, jankapunkt commented on .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
> +https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor
We should change this to:

> Before reporting a bug, please check for existing or closed issues
first.

2023-06-05 20:42 UTC, jankapunkt commented on .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
> +- [ ] A **simple** reproduction! (Must include the Github repository and steps to reproduce the issue on it.)
We should change `(Must include the Github repository and steps to reproduce the issue on it.)` to

> (Must either include a minimal code example or a link to a  Github repository with steps to reproduce the issue on it.)

2023-06-05 20:42 UTC, jankapunkt commented on .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
> +### Independent packages
This section can be removed entirely

2023-06-05 20:42 UTC, jankapunkt commented on SECURITY.md
> +| Version | Support Status
Please change this to

```
| Version | Support Status
| ------- | --------------
| 3.x.y   | ✅  all security issues
| >=2.5   | ✅  all security issues
| <2.5   | 🚧  only critical security issues
| <= 2  | ❌  no longer supported
```

2023-06-05 20:43 UTC, jankapunkt commented
@Veldergard in order to update this PR with your changes you simply implement your changes, commit them and push them to this branch, then this page will automatically update.

2023-06-06 07:55 UTC, Veldergard commented
@jankapunkt i commited changes.
@Grubba27 @denihs check for other issues pls

2023-06-06 09:35 UTC, StorytellerCZ approved these changes

2023-06-06 14:45 UTC, Grubba27 commented
Talked with @fredmaiaarantes and is okay to use [security@meteor.com](mailto:security@meteor.com)

2023-06-07 07:25 UTC, merged

2023-06-07 07:26 UTC, jankapunkt commented
Congratulations @Veldergard to your first merged pull request :tada: